version: "3.9" # optional since v1.27.0
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dockbox/server
    ports:
      - "5000:5000"
    depends_on:
      - "database"
    environment:
      - ENVIRONMENT=development
      - PORT=5000
      - DATABASE_NAME=prod
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - S3_BUCKET_KEY=srihari-shopify-challenge
      - AWS_ACCESS_KEY_ID=<PUT ACCESS KEY ID HERE>
      - AWS_SECRET_ACCESS_KEY=<PUT SECRET ACCESS KEY HERE>
      - AWS_DEFAULT_REGION=us-east-1
      - JWT_SECRET=random_secret

  database:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=password
